/**
 * Two ways to provide load-test fixtures:
 *
 *  1) BYO env (CI-friendly)
 *     SYROTP_BASE_URL, SYROTP_PUBLIC_KEY, SYROTP_SECRET_KEY,
 *     SYROTP_RECEIVER_1_ID, SYROTP_RECEIVER_1_KEY, SYROTP_RECEIVER_1_MSISDN,
 *     SYROTP_RECEIVER_2_*  (only required for scenario C)
 *
 *  2) DB prep (developer-friendly)
 *     SYROTP_BASE_URL, DATABASE_URL, MASTER_ENCRYPTION_KEY,
 *     and we materialize the fixtures via direct DB inserts.
 *
 * The tool prefers (1) if those env vars are present, otherwise falls back
 * to (2). It never reads secrets from anywhere except the environment.
 */
import { randomBytes } from "node:crypto";
import postgres from "postgres";
import { ulid } from "ulid";

export interface Receiver {
  id: string;
  msisdn: string;
  signingKey: string;
}

export interface Fixtures {
  baseUrl: string;
  publicKey: string;
  secretKey: string;
  receivers: Receiver[];
  /** True if this run created its own fixtures and should clean them up. */
  ephemeral: boolean;
  cleanup?: () => Promise<void>;
  /**
   * v0.8 PR #37 — startVerification rejects any phone without a
   * `verified` row in `phone_bindings` for the calling app. The
   * loadtest scenarios use deterministic phones generated by
   * `phoneFromIndex(i)`; this hook lets the runner pre-seed those
   * bindings before scenario start. Real consumers never see this
   * — it's a CI-only direct DB write that mirrors what the binding
   * ceremony would do, just faster than running the full SMS
   * round-trip for thousands of synthetic phones.
   */
  seedBindings?: (phones: string[]) => Promise<void>;
}

export async function loadFixtures(opts: { neededReceivers: number }): Promise<Fixtures> {
  const baseUrl = required("SYROTP_BASE_URL");

  const byo =
    !!process.env.SYROTP_PUBLIC_KEY &&
    !!process.env.SYROTP_SECRET_KEY &&
    !!process.env.SYROTP_RECEIVER_1_ID;

  if (byo) return loadByoFixtures(baseUrl, opts.neededReceivers);
  return prepFixtures(baseUrl, opts.neededReceivers);
}

function loadByoFixtures(baseUrl: string, needed: number): Fixtures {
  const receivers: Receiver[] = [];
  for (let i = 1; i <= needed; i++) {
    const id = process.env[`SYROTP_RECEIVER_${i}_ID`];
    const key = process.env[`SYROTP_RECEIVER_${i}_KEY`];
    const msisdn = process.env[`SYROTP_RECEIVER_${i}_MSISDN`];
    if (!id || !key || !msisdn) {
      throw new Error(
        `BYO env mode missing SYROTP_RECEIVER_${i}_{ID,KEY,MSISDN}. ` +
          `For multi-receiver scenarios, run bootstrap.js once per receiver and export each set.`,
      );
    }
    receivers.push({ id, msisdn, signingKey: key });
  }
  return {
    baseUrl,
    publicKey: required("SYROTP_PUBLIC_KEY"),
    secretKey: required("SYROTP_SECRET_KEY"),
    receivers,
    ephemeral: false,
  };
}

/**
 * Build fixtures by talking directly to Postgres. We replicate exactly the
 * shape the production bootstrap script writes, so a load-tested server is
 * indistinguishable from a real deployment.
 */
async function prepFixtures(baseUrl: string, needed: number): Promise<Fixtures> {
  const dbUrl = required("DATABASE_URL");
  const masterKeyHex = required("MASTER_ENCRYPTION_KEY");
  if (!/^[0-9a-fA-F]{64}$/.test(masterKeyHex)) {
    throw new Error("MASTER_ENCRYPTION_KEY must be 64 hex chars (32 bytes)");
  }

  const sql = postgres(dbUrl, { max: 4 });
  try {
    const appId = `app_${ulid()}`;
    await sql`INSERT INTO apps (id, name) VALUES (${appId}, ${"loadtest-" + new Date().toISOString()})`;

    const pk = `pk_live_${randomChars(32)}`;
    const sk = `sk_live_${randomChars(32)}`;
    await sql`
      INSERT INTO api_keys (id, app_id, kind, key_hash, key_prefix, label) VALUES
        (${"key_" + ulid()}, ${appId}, 'public', ${hashApiKey(masterKeyHex, pk)}, ${pk.slice(0, 12)}, 'lt-public'),
        (${"key_" + ulid()}, ${appId}, 'secret', ${hashApiKey(masterKeyHex, sk)}, ${sk.slice(0, 12)}, 'lt-secret')
    `;

    const receivers: Receiver[] = [];
    const operators = ["syriatel", "mtn", "operator-c", "operator-d"];
    for (let i = 0; i < needed; i++) {
      const id = `rcv_${ulid()}`;
      const signingKey = randomBytes(32).toString("hex");
      const wrapped = aesGcmWrap(masterKeyHex, signingKey, `receiver:${id}`);
      const lastDigits = String(8000000 + i).padStart(7, "0");
      const msisdn = `+96399${lastDigits.slice(-7)}`;
      await sql`
        INSERT INTO receivers (id, app_id, name, operator, msisdn, secret_hash, enabled, last_heartbeat_at)
        VALUES (${id}, ${appId}, ${"lt-rcv-" + (i + 1)}, ${operators[i % operators.length]!},
                ${msisdn}, ${wrapped}, true, now())
      `;
      receivers.push({ id, msisdn, signingKey });
    }

    return {
      baseUrl,
      publicKey: pk,
      secretKey: sk,
      receivers,
      ephemeral: true,
      async cleanup() {
        const sql2 = postgres(dbUrl, { max: 1 });
        try {
          // Cascading FKs do the rest.
          await sql2`DELETE FROM apps WHERE id = ${appId}`;
        } finally {
          await sql2.end({ timeout: 5 });
        }
      },
      async seedBindings(phones: string[]) {
        if (phones.length === 0) return;
        // Bulk-insert verified bindings tied to the first receiver.
        // Enforcement at startVerification is per (app_id, phone)
        // — receiver_id on the binding doesn't have to match the
        // receiver the router eventually picks, so any receiver
        // works for the loadtest's synthetic phones.
        const recvId = receivers[0]!.id;
        const sql3 = postgres(dbUrl, { max: 4 });
        try {
          // Chunk to avoid hitting Postgres's bind-parameter limit.
          const CHUNK = 5000;
          for (let i = 0; i < phones.length; i += CHUNK) {
            const slice = phones.slice(i, i + CHUNK);
            const rows = slice.map((phone) => ({
              id: `pbn_${ulid()}`,
              app_id: appId,
              receiver_id: recvId,
              phone_e164: phone,
              status: "verified" as const,
              nonce: `lt-seed-${randomBytes(8).toString("hex")}`,
              expires_at: new Date(Date.now() + 60 * 60 * 1000),
              bound_at: new Date(),
            }));
            await sql3`INSERT INTO phone_bindings ${sql3(rows, "id", "app_id", "receiver_id", "phone_e164", "status", "nonce", "expires_at", "bound_at")}`;
          }
        } finally {
          await sql3.end({ timeout: 5 });
        }
      },
    };
  } finally {
    await sql.end({ timeout: 5 });
  }
}

function required(name: string): string {
  const v = process.env[name];
  if (!v) throw new Error(`missing env: ${name}`);
  return v;
}

const ALPHA = "abcdefghijklmnopqrstuvwxyz0123456789";
function randomChars(n: number): string {
  const buf = randomBytes(n);
  let out = "";
  for (let i = 0; i < n; i++) out += ALPHA[buf[i]! % ALPHA.length];
  return out;
}

// -- crypto primitives, kept self-contained so the load tool has no internal
//    dependencies on the server package's source layout. ----------------

import { createCipheriv, createHmac } from "node:crypto";

function hashApiKey(masterKeyHex: string, raw: string): string {
  const key = Buffer.from(masterKeyHex, "hex");
  return createHmac("sha256", key).update(`api_key:${raw}`).digest("hex");
}

function aesGcmWrap(masterKeyHex: string, plaintext: string, aad: string): string {
  const key = Buffer.from(masterKeyHex, "hex");
  const iv = randomBytes(12);
  const cipher = createCipheriv("aes-256-gcm", key, iv);
  cipher.setAAD(Buffer.from(aad, "utf8"));
  const ct = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  return ["v1", b64u(iv), b64u(tag), b64u(ct)].join(".");
}

function b64u(buf: Buffer): string {
  return buf.toString("base64").replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
